apiVersion: v1
kind: Service
metadata:
  name: simple-web
spec:
  selector:
    app: simple-web
  type: LoadBalancer
  ports:
    - name: simple-web
      protocol: TCP
      port: 32000
      targetPort: 8080
      nodePort: 30000
